---
title: "Atlas de servicios ecosistémicos de espacios verdes en la GAM - Mamíferos"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(ggplot2)
library(flexdashboard)
library(sf)
library(tmap)
library(leaflet)
library(knitr)
library(kableExtra)

mammalia = st_read("https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos/master/biodiversidad/presencia/mammalia.geojson")

table_mammalia_spp_count = table(mammalia$species)
df_mammalia_spp_count = as.data.frame(table_mammalia_spp_count)

# Se extraen las especies ordenadas por frecuencia
df_mammalia_spp_count.order <- order(df_mammalia_spp_count$Freq, decreasing=TRUE)

# Se genera un nuevo data frame ordenado
df_mammalia_spp_count.order.freq <- df_mammalia_spp_count[df_mammalia_spp_count.order,]


```

Column {data-width=550}
-----------------------------------------------------------------------

### Mapa de distribución
```{r}
# tmap_mode("view")
# map_mammalia
leaflet() %>% 
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>% 
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addCircleMarkers(data = mammalia,
                   stroke = F,
                   radius = 4,
                   fillColor = 'red',
                   fillOpacity = 1,
                   popup = paste(mammalia$order, mammalia$species, sep = '<br/>')) %>%
  addLayersControl(baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "Imágenes de ESRI")) %>%
  addMiniMap(
    toggleDisplay = TRUE,
    tiles = providers$Stamen.TonerLite
  )
```

Column {data-width=450}
-----------------------------------------------------------------------

### Registros de presencia de especies
```{r}
valueBox(nrow(mammalia), icon = "fa-pencil")
```

### Especies
```{r}
valueBox(length(unique(mammalia[["species"]])), icon = "fa-pencil")
```

### Registros de presencia de especies
```{r}
# Se extraen las observaciones ordenadas por orden alfabético de especies
mammalia.orden <- order(mammalia$species)

# Se genera un nuevo data frame ordenado
mammalia.ordenadoxespecie <- mammalia[mammalia.orden,]

# Se formatea la tabla con el nuevo data frame
kable(
  mammalia.ordenadoxespecie[, c("species","genus","family","order","year")], 
) %>%
kable_styling() %>%
scroll_box(
  width = "600px", 
  height = "250px", 
  fixed_thead = TRUE
)
```

### Especies más registradas
```{r}
#barplot(
#  height=df_mammalia_spp_count.order.freq$Freq, 
#  names.arg=df_mammalia_spp_count.order.freq$Var1,
#  xlim = c( 0 , 10 )
#)

ggplot(df_mammalia_spp_count[1:4,], aes(x=reorder(Var1, -Freq), y=Freq)) +
  xlab("Especies") + 
  ylab("Frecuencia") +  
  geom_col() +
  geom_text(aes(label=Freq), vjust=-0.3, size=3.5)

```